spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/logintest?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  h2:
    console:
      enabled: true
